### ISSUE TITLE
Vue route/component(s) for candidate

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#10]
There is an important distinction to make about `candidates` vs `listings`

* any `listing candidate` is not an actual `listing` until it is voted "in"
* any `listing candidate` is simply a `candidate` until it is voted "in"

Other candidates do exist:
* reparam
* challenge

Therefore a UI/UX decision must be made. Does the route `../candidate/hash` and the route `.../listing/hash` show the same thing? Or do we choose to show nothing on the `listing/hash` for listings which are still in their applicant phase?

NOTE: Other candidates do not have the permanence that listings do. A `challenge` or `reparam` simply vanish when voting is done...

**Comment by ReidWilliams** [comment]
My preference is to have one consistent route that works for both `candidates` and `listings`. 

The page can render different elements depending on whether it's a `candidate` or a voted `listing`. A `listing` would have the option to buy, (and if the user is the owner, delete). A `candidate` would show the candidate metadata (title, description) but have some words that say that it is still a candidate and not allow buying.

The question is what is that route. Finding a `candidate` at `.../listing/hash` is abusing the nomenclature a bit. I'm fine with that for now.

**Comment by robrobbins** [comment]
there cannot be just one, that is restfully incorrect

that does not mean that `.../listing/hash` does not work for a candidate. sure it can - show the candidate stuff if a candidate, and show the listing stuff if not

there will be a `.../candidate/hash` route that works as well if it is still an applicant
