### ISSUE TITLE
Implement the listing component

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#112]
I think what we're seeing is that we may use this component configured differently for different routes, e.g. a user's listings vs all listings.  The component should be configurable to render any kind of listings, e.g. candidates or listings, and by whatever context, e.g. by a single user or by all users, requested.

**Comment by thirtyaughtsix** [comment]
This is going to require creating a dirt simple `FfaListingView` component (probably need to suffix _View_ since the model class is already called `FfaListing`).  Like just a bunch of `<span>`s in a `<div>`.

**Comment by MelvinMallari** [comment]
#144
