### ISSUE TITLE
duplicate ethereumDisabled getter

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#116]
this exact code appears in two places:
```
  get ethereumDisabled() {
    return typeof ethereum === 'undefined' || typeof ethereum.selectedAddress === 'undefined'
  }
```

Needs to be pulled out into a functionModule.

**Comment by thirtyaughtsix** [comment]
Also I wrote the original test incorrectly.  `ethereum.selectedAddress` has type `string` that means it can *NEVER* be undefined.  The test should be if the string has value (is non-null and has length > 0)

**Comment by MelvinMallari** [comment]
#128
