### ISSUE TITLE
Complete Buy Drawer.  Task poller integration phase 2.

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#178]
See #161.  Need to go to [figma v4](https://www.figma.com/file/cakBXdrJavD5KIb4jrea7F/ffa-v4?node-id=0%3A1) for wires.

Most of this is complete.  What remains is wiring in the call to `requestDelivery` via the task poller and integrating the task poller for all ethereum transactions.  See #262, #263.

**Comment by MelvinMallari** [comment]
#312
