### ISSUE TITLE
FE <--> BE integration: view a single candidate

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#229]
See https://github.com/computablelabs/capi/issues/9

Right now we're going directly to chain to get candidate data.  Figure out what the delta between that and the response from this endpoint is and adapt as necessary.

**Comment by robrobbins** [comment]
I closed #9 in CAPI, as you already have 
    /listings?owner=xxx
from which you can just grab the one you want. *or)
    /listings?block-number=xxx
using your latest block number if you have already done a get on `listings` before

**Comment by MelvinMallari** [comment]
#231
