### ISSUE TITLE
Computable.js integration for upload

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#23]
What protocol methods do we care about for the the upload? If we are focused solely on the uploaded asset itself likely this is just 

* `listingContract.list`

Need to figure out how we want to generate the `listingHash` and what exactly it is we are hashing

* do we let the client provide some "original string" then hash that?
* does the client want a means to remember this to prevent the user from not remembering what their own listingHash is... 
* if yes on the above is it the client's responsibility solely or should it involve the datatrust?

**Comment by thirtyaughtsix** [comment]
rob [02:06]
:shipit:

we'll use that. we'll `keccak(address, title)`
and that will be the listingHash

**Comment by thirtyaughtsix** [comment]
note to self: `keccak(keccak(address), keccak(title))`

**Comment by thirtyaughtsix** [comment]
so after talking with @ReidWilliams, he and i think that `keccak(keccak(address)), keccak(unix_timestamp))` is preferable since it has a high probability of uniqueness negating a need a for a pre-submission test of `isListed` and `isCandidate`, i.e. let non-unique hashes fail.

**Comment by robrobbins** [comment]
no.

**Comment by thirtyaughtsix** [comment]
fine.

**Comment by thirtyaughtsix** [comment]
See #43 for validation.  still waiting on wallet stuff to gen the hash
