### ISSUE TITLE
Add fields to response payload from get request to `/candidates/application`

### ISSUE THREAD

**Issue by MelvinMallari** [computablelabs/ffa-frontend#230]
`get` to `/candidates/application` current payload object:
```
{
  "description": "banana",
  "title": "Banana banana",
  "license": "MIT",
  "listing_hash": "0xfff9297b3cbe78ea9ddf1b48817f70f4a9a8ffc7fa4f36e1b9655a513c3cbb36",
  "file_type": "unknown",
  "tags": null
},
```
Additional Requested Fields:
* `size` - File Size, bytes
* `owner` - Can make contract calls ad hoc, but more efficient to have available in aggregate
* `shareDate` - Upload Date

**Comment by robrobbins** [comment]
I wouldn't specify that this be `candidates/application` *specifically*. I would argue that it's simply any permutation of `/candidates...`.

* `owner` is present in the `CandidateAdded` event so no work to be added there. *yes*
* `shareDate` is likely the block timestamp which *i believe* is present when grepping the logs for this event. *likely*
* size may be an issue as i we'll need to see if this turns this aggregate endpoint into a doomed `N+1 query` so *TBD* on this one

**Comment by robrobbins** [comment]
owner is added.

other two are TBD
