### ISSUE TITLE
Computable.js Integration for Listing getters

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#24]
Assuming that an upload succeeds a candidate will be created. This creates a number of getters that are necessary for showing the user the state of said candidate

* Listing contract
    * getListing
    * isListing
* Voting contract
    * isCandidate
    * getCandidate
   
We'll break out `vote` into a separate ticket so it may be that all the candidate issues belong there...

**Comment by thirtyaughtsix** [comment]
The Listing contract is imported into a class in #27.  The intention is to encapsulate this class in the `vuex` module `ListModule`.
