### ISSUE TITLE
Integrate the task poller (phase 1)

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#246]
Phase 1 covers two integration touch points:
1. create a listing
2. vote on a listing

**Comment by thirtyaughtsix** [comment]
File listing is a bit of an odd duck because we are still relying on dropzone to manage the actual http form upload.  In `FileUploader.vue`, we register a callback for the upload succeeded event: 
```
  private succeeded(f: DropzoneFile, resp: string) {
    this.uploadModule.setStatus(ProcessStatus.Complete)
  }
```

It's inside this method that the datatrust response should be parsed and a new `DatatrustTask` should be created and added to the `DatatrustTaskModule`.  The `TaskPollerManager` is subscribed to that event.

**Comment by MelvinMallari** [comment]
#312
