### ISSUE TITLE
EVM poller

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#254]
We need an evm event poller that 

- load sufficiently recent events at boot, i.e. doesn't read the entire history of the chain
- continues to poll and read evm events
- reconciles mined transaction events with a vuex module that keeps track of pending transactions.

**Comment by robrobbins** [comment]
* you prob need to state exactly which events you need to get-past-events for
* you can use block numbers to stop how far back in time you wanna go
* you can ask web3 what the current block is

* polling. i do think long polling is still the way to go here. we will have the possibility of establishing websocket, but, geth (and parity) have a bit of a reputation to go with their implementations of websockets. i'd say poll first (cuz we'll likely want it as a fallback) and look into sockets later

**Comment by thirtyaughtsix** [comment]
This is most likely going to move to capi.

**Comment by thirtyaughtsix** [comment]
Closing.
