### ISSUE TITLE
Repair vuex state issues preventing state from rendering in vue dev tools

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#268]
See [https://github.com/vuejs/vue-devtools/issues/967](https://github.com/vuejs/vue-devtools/issues/967)

**Comment by narkan** [comment]
I'm still having this on Ubuntu 18.04 with Chrome Version 80.0.3987.149 (Official Build) (64-bit).

Same issue as https://github.com/vuejs/vue-devtools/issues/967

**Comment by narkan** [comment]
> I'm still having this on Ubuntu 18.04 with Chrome Version 80.0.3987.149 (Official Build) (64-bit).
> 
> Same issue as [vuejs/vue-devtools#967](https://github.com/vuejs/vue-devtools/issues/967)

Seemed to resolve by disabling Vue Performance DevTools (fix shown here: https://github.com/vuejs/vue-devtools/issues/914)
