### ISSUE TITLE
metamask ethereum personal_sign spike

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#269]

**Comment by robrobbins** [comment]
Notes:
* you guys are presenting a message for them to sign. @rbharath wants something dynamic in it. @ReidWilliams suggested  <insert TRON suggestion here>. You are going to send this message as is to CAPI (or you can hash it, doesn't matter)
* the MM action for sign should return you a hash, keep it as you need to send it to CAPI
* you'll be sending CAPI the users publick_key as well

**Comment by robrobbins** [comment]
Regarding the action on your end:
* ideally you can go down to RPC level like we did with send via `personal_sign`
* if you can't a smelly solution exists. You can reference _their_ old web3 and use it. Obviously not what we want, but you could always make some interface to serve as a go-between with it... like i said _should_ be able to use RPC and the `ethereum` provider...

**Comment by MelvinMallari** [comment]
#277
