### ISSUE TITLE
Drawers should be able to size to fit their content.

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#283]
As a user steps through a given flow (for example creating a new listing candidate), the height of the drawer content changes.

Right now, the drawer is a fixed size. The height of the drawer should change as its content changes. 

This could just be attaching different css classes as the drawer moves through states.

**Comment by thirtyaughtsix** [comment]
pr #391 experiments with setting the desired drawer height in the vuex module.  requires redundant css blocks which is blah but it seems to "work good."
