### ISSUE TITLE
In new listing flow, once listing transaction and mining are complete, render as listing candidate

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#305]

**Comment by ReidWilliams** [comment]
What this means is:
- URL should change from `/listings/new` to `/listings/candidate/0x...`
- View should include a status message (open for voting) and a Listing/Details tab above the view.

Talk to me if you're not sure what the status message is.

**Comment by thirtyaughtsix** [comment]
Do you want this to happen in the "middle" of the new listing drawer process, specifically when the listing transaction is mined, i.e. the first process completes?  

That's an overhaul of `CreateNewListingPage` and its associated drawer (maybe a 4 out of a 10 difficulty).

I'm starting to think this is the _required_ direction.  Here's the rub: there is no way to repopulate Dropzone to set up an abandoned listing - browser security bs prevents us from recording and replaying the file input selection.  So we'll need a UX path that allows people to associate a file with an on-chain listing or we'll end up with zombie listings that, in the least, eat user gas.  Such a UX path requires a route which is exactly where a promote from listing transaction would go. 

Thoughts?

**Comment by ReidWilliams** [comment]
I was thinking the moment that the page gets promoted is *after* both the `list` contract call is mined and the upload to datatrust is complete.

Users should be warned before leaving the page while the upload is in progress, and to keep things simple, they should be warned before leaving before either of the two (list, upload) steps are complete.

I guess the zombie edge case still exists. We can warn but can't stop them from leaving and if they do leave after `list` has been submitted but before the upload is complete, they will get a zombie listing. 

I think this zombie state is equivalent to if the upload finishes but for whatever reason the datatrust doesn't call `setDataHash`. So maybe we don't consider a proto-candidate to be a candidate until both `list` and `setDataHash` are called.

The question then is wtf to show to users in the short interim where `list` and upload are complete but `setDataHash` hasn't been mined? Also, whatever we're rendering to the user, does it have a unique url apart from `/listings/new` that they can revisit?

Let's chat when you're up.
