### ISSUE TITLE
Update vote new candidate drawer to follow same UI pattern as vote on challenge

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#310]
1. Vote on new candidate drawer should render blockchain and drawer messages.  
2. Should not self close.

See #433

**Comment by ReidWilliams** [comment]
- This might already be done

**Comment by ReidWilliams** [comment]
This drawer should use same components and pattern as the challenge vote drawer: `StatusButton`, `BlockchainExecutingMessage`, `DrawerMessage`.

Should approve spending of CMT if needed before calling vote method.

**Comment by thirtyaughtsix** [comment]
@ReidWilliams I updated the description.  Please confirm that it's correct.  

One thing I noticed is that the challenge drawer doesn't look right either.  Do we need a separate issue for that as well?

**Comment by ReidWilliams** [comment]
Yeah maybe, I thought it did, but I may be wrong. 

In any case, the gold standard for what should be in both voting drawers (candidate and challenge) is the "Vote on a challenge" flow in `dev.sketch` in the `dev` branch of `ffa-design`.

Other than language, the two types of votes should be identical. Feel free to leave formatting text and spacing (margin, padding, etc) to me.
