### ISSUE TITLE
VerticalSubway doesn't render title

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#398]
When a candidate has been listed in the market, under its details tab, the `listingTitle` prop passed to `VerticalSubway` is an empty string, resulting in no title being rendered.

**Comment by thirtyaughtsix** [comment]
did this automagically fix itself?

**Comment by ReidWilliams** [comment]
No, still missing. It works when something is a candidate, only broken when it is a listing.

**Comment by ReidWilliams** [comment]
@thirtyaughtsix @MelvinMallari I unassigned myself from this, so one of you should take it.
