### ISSUE TITLE
Flashes display is inconsistent

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#408]
I think the create new listing page is the only page w/ flash display.  Should we move flashes to the main app?  Should there be css that stacks the flashes z-space-wise?  Should we just ditch them altogether?

**Comment by ReidWilliams** [comment]
Ditch em. @MelvinMallari can I assign to you?

**Comment by ReidWilliams** [comment]
Left myself assigned too, for whomever gets to it first.

**Comment by MelvinMallari** [comment]
As discussed in person with Reid - we'll keep error flashes, and remove all else.

**Comment by MelvinMallari** [comment]
#522
