### ISSUE TITLE
Drawer renders empty after navigating from details to listing

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#430]
To reproduce:

- go to `http://.../share`
- go through the flow
- once new candidate is created, and url becomes `http://.../listings/candidates/<hash>/created`, keep drawer open
- navigate to Listing tab

The drawer renders empty except for the close button.

Correct behavior is to keep rendering drawer with "Voting is open for this listing" even if a user navigates to the Listing tab. OR if easier, close the drawer when the user navigates to the Listing tab.

See #433

**Comment by thirtyaughtsix** [comment]
@ReidWilliams I _think_ this is resolved but **other** similar issues likely exist.  Let's use this issue to track them as they are discovered.

**Comment by ReidWilliams** [comment]
It still happens as of `master` `de02c0`.

**Comment by ReidWilliams** [comment]
Fixed now.
