### ISSUE TITLE
Clean up VerticalSubway, VotingDetails

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#445]
See #433

**Comment by ReidWilliams** [comment]
@thirtyaughtsix not sure what you have in mind, but there are some UI issue with both of these.

- The orientation of the subway lines breaks when there is a challenge card.
- `VotingDetails` needs to work for both new candidate voting and challenge voting. (That or make a new component for challenge voting).
- Ideally the subway should be able to handle multiple challenge/votes.
