### ISSUE TITLE
reset uploadModule and newListingModule in CreateNewListing

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#489]
i think the file attachment from a previous session is misleading and leads to a failed upload (the file isn't actually attached).  we should reset the modules and force users to wander away from the new listing page to reselect a file.

**Comment by ReidWilliams** [comment]
Is this the same as https://github.com/computablelabs/ffa-frontend/issues/489?

If I'm understanding right, we should make sure that once a user creates a candidate or navigates away from the `/share` route, the dropzone resets. This means the rendered dropzone resets to the empty rendered state and any models are reset (which may already be happening).
