### ISSUE TITLE
[MASTER] Create a listing candidate

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/ffa-frontend#5]
**A user can create a listing candidate using a browser + Metamask**

Master ticket complete when:

Assume:
- User has Metamask installed and set up with at least one private key/address

User can then:

1. Navigate to `https://.../new` which creates a listing hash and redirects to `https://.../listing/<listhash>`
2. See an empty listing
3. Drag a file onto the page to start the upload process
4. See the progress of the upload while...
5. Entering listing details including title, description, tags, license
6. Click *List* button once file upload is complete
7. Use Metamask popup to sign transaction (`Listing.list`)
8. See listing details (as they will appear when viewing the listing) and a message saying that mining is happening. User can close browser and come back to see progress at this point.
9. Once mining is complete, message now says voting is happening
10. Once voted in, listing appears as it will for any user. If listing is rejected, message says listing has been rejected.

**Comment by ReidWilliams** [comment]
As I wrote this out, a couple of things came up that still need to be addressed:
- If a listing application fails, protocol forgets about it (right?). How does a listing owner know it failed? Does `https://.../listing/<listing hash>` temporarily remain available with a message about the fail? Does the user need to visit `https://.../address/<their-address>` where failed listings are part of the summary of their activities?
- How will the owner of a failed listing know why it failed?

**Comment by ReidWilliams** [comment]
Updated to incorporate Tuesday's discussion. This is v1; we'll add more later.

**A user can create a listing candidate using a browser + Metamask**

Assume:

User has Metamask installed and set up with at least one private key/address
User can then:

1. Navigate to `https://.../new` which creates a listing hash and redirects to `https://.../listing/<listhash>`
2. See an empty listing with placeholder title and description
3. Drag a file onto the page (button that opens file chooser not necessary now)
4. Page indicates it has "received" file by displaying the file name. File isn't uploaded yet.
5. Edit title and description
6. Click List
7. Page pops up metamask signing dialog
8. In parallel, page is posting listing details and file to datatrust
9. After signing, page displays upload progress %
10. After upload/post to datatrust is complete, display message that mining is happening
11. After block is mined, display message that voting is happening

User obviously has to keep browser open while the upload happens, but should be able to close browser once the upload is done.

For this version, focus on getting browser + metamask + datatrust + eth node all playing nice. We'll bring in more features and nice CSS / layout later.

**Comment by robrobbins** [comment]
* #8 
* #9
