### ISSUE TITLE
Move Start Listing button to the drawer

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#52]
Let's move `StartListingButton` from `FileMetadata` to the `ListDrawer`.

That means `ListDrawer` will need two states:

1. StartListingButton state
2. Processing state

The question is gonna be should this be handled in `ListDrawer` (I believe that's correct) or by fiddling with the Vue slot in `Drawer` that `ListDrawer` occupies.

**Comment by thirtyaughtsix** [comment]
<img width="747" alt="Screen Shot 2019-07-30 at 12 51 09 AM" src="https://user-images.githubusercontent.com/1030479/62066540-28a6bb00-b264-11e9-9035-ee0115f3975f.png">

**Comment by thirtyaughtsix** [comment]
and let's apply the bulma style to the button (https://bulma.io/documentation/elements/button/)

(spoiler alert: the class is 'button')

**Comment by MelvinMallari** [comment]
#64
