### ISSUE TITLE
Audit Vue components

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#73]
Identify all Vue components and Vuex modules that need a refactor:

We need to flag every class that needs to have methods pulled out into a separate pure function container class, basically just a module with funs.

So that's anything in a component that isn't a:  Vue property, Vue data, Vue getter, Vue named event handler.

Put the list here in the convo of the issue.

References #67

**Comment by MelvinMallari** [comment]
* FileLlister.vue
  * list()
* FileMetaData.vue
  * validateTitle()
  * onTitleChange()
* FileUploader.vue
  * initializeDropzone()
  * upload()
  * renameFile()
  * fileAdded() 
  * fileRemoved()
  * preprocessFileData()
  * uploadProgressed()
  * succeeded()
  * failed()
* StartListingButton.vue
  * startListing()
* FfaTag.vue
  * deleteTag()
* FfaTagger.vue
  * addTags()
* FlashMessage.vue
  * remove()
* Navigation.vue
  * setPublicKey()
* Status.vue
  * execute()
