### ISSUE TITLE
Refactor Vue components

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#75]
Use the list from #73 and refactor each Vue component.  One component -> one PR.

New funs should be pure so they can be static.  Let's create a new top level folder called `@/functionModules`.  Component function modules probably belong in `@/functionModules/components` while Vuex modules probably belong in `@/functionModules/vuexModules/`.

Don't forget to add specs!

**Comment by MelvinMallari** [comment]
#87 #86 #83
