### ISSUE TITLE
Protocol: Listing -> new

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#9]
Re: #5 bullet 1 and bullet 6

* How is the listing hash generated?
* How do we associate that listing hash with user's ETH account
* do we plan to keep a cache of them?
* if so where? (datatrust/client...)
* how does frontend want to handle notification of transaction completion/failure

**Comment by ReidWilliams** [comment]
There are going to be listing hashes that protocol doesn't yet know about, but still need to be tracked. For example, a `candidate` that has been submitted to datatrust, and txn is sent to Eth network, but not yet mined.

Another example, a `candidate` application fails. Protocol forgets the candidate after `resolveApplication` is called.

For both these cases, and maybe others, we'll need a way for the user to see that status of their `candidate` but protocol won't know about them.

**Comment by robrobbins** [comment]
i don't think there's any reason for a candidate to submit a listing to the datatrust exclusive of the call to begin its candidacy. i.e the call to protocol `list` and datatrust `list` happen together.

on tracking hashes:

there may not be any need to track them outside protocol. 

* user has a hash that is not a listing or a candidate (like your above example)
* dapp can check the event logs for a `failedApplication` or `challengeSucceeded` event for that hash determining its fate.
