### ISSUE TITLE
Prompt user to `connect` if `ethereum.selectedAddress` is falsy

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#90]
Along with #89 this should provide us with a fullproof way of having a 'connected' user.

**Comment by robrobbins** [comment]
@ReidWilliams there may even be a "UI-Less" way of doing this - since MetaMask has its own pop-up. We can, at any point just check for that global var, and if it's not there call for the popup.

**Comment by ReidWilliams** [comment]
Here's what I have in mind for this:

- User has metamask, but has not yet connected? → render a connect button in top right in the nav component.
- User is connected? → render the user's [jazzicon](https://github.com/danfinlay/jazzicon) for their connected address.
- No metamask? → render _Get Started_ which (later) will link to a getting started page.

**Comment by robrobbins** [comment]
:+1: 

@MelvinMallari there's likely a way to use the user's public key to render the jazzicon the way MetaMask does so that the two icons are the same.

**Comment by MelvinMallari** [comment]
#115
