### ISSUE TITLE
Implement "Block Paging"

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-frontend#93]
Likely a "Master" ticket as this will vary (I think) for each "Past Event" that we grep the logs for.

For example consider this scenario

    ( assume candidateAddedFromBlock is initialized to 0 somehow )
    let latestBlock = await web3.eth.getBlock('latest')

    votingContract.deployed.getPastEvents('CandidateAdded', {
        filter: { owner: ethereum.selectedAddress }, 
        fromBlock: candidateAddedFromBlock,
        toBlock: latestBlock.number
    })

    candidateAddedFromBlock = latestBlock.number

Here we set what will initially be a `from 0 to latest` grep the first time, but subsequent calls will become a "paged" `previousLatest to currentLatest`

**Comment by robrobbins** [comment]
https://web3js.readthedocs.io/en/v1.2.1/web3-eth-contract.html#getpastevents

**Comment by robrobbins** [comment]
even with the actuall log grepping moving to datatrust this is likely still relevant as some way to specify blocks which may get passed to and from datatrust api should exitst (particularly since any api is stateless)

@rekibnikufesin

**Comment by robrobbins** [comment]
latest thoughts on this:

URL -> `listings/0xUs3r`

datatrust, seeing no block data in the query assumes this is a `fromBlock; 0, toBlock: 'latest'`. It then sends back all the user's listings from 0 to N (N being the actual latest blocknumber)
**It also sends back N, which the client stores (let's say it was 1000000)**

_time passes_

URL -> `listings/0xUs3r?block=1000000`

datatrust, seeing `block` is 1M in the query will only fetch that user's listings `fromBlock: 1000000, toBlock: 'latest'. **And send back the newest 'latest'**

**Comment by thirtyaughtsix** [comment]
superseded by #644 and #651
