### ISSUE TITLE
Log grepping for candidates

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#94]
Use the log grepping:

> rob:cactus: 23:16:
> but as far as listings.all
> i think its getPastEvents for Votings `CandidateAdded` event
> for FFA that call is literally `votingContract.deployed.getPastEvents('CandidateAdded', { filter: {  owner: ethereum.selectedAddress }, fromBlock: fooBlock, toBlock: 'latest'})`

Also see #93

**Comment by robrobbins** [comment]
so for this to be what @ReidWilliams wants you have to make a couple of calls:

1. the above `voting` one to get candidates
2. call `listingContract.deployed.getPastEvents` to get any that are listed (as they will not show up as candidates`. The actual event name for that one is `Listed`

https://github.com/computablelabs/computable/blob/master/contracts/Listing.vy#L54

so with both candidates and listings you can show them 'all' likely with some UI annotating which are `candidates`

worth noting that some of the `candidates` may be in an unresolved state so up to you all how you want to filter it. Just look at the Vyper contracts when in doubt for what events are available. there's a bunch of them

**Comment by thirtyaughtsix** [comment]
This is the actual contract integration, the `functionModule` and the `@MutationAction` integration.

**Comment by thirtyaughtsix** [comment]
As per convo w/ @rekibnikufesin earlier, datatrust will handle the event call to protocol and then fill those results with data from dynamo.
