### ISSUE TITLE
Alter `FfaListingsModule`

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-frontend#95]
Needs to add two new members:

- `public lastCandidatesBlock: number = 0`
- `public lastListedBlock: number = 0`

Need to add a `FfaListingStatus` enum to `FfaListing` as a status field.  Right now we have three statuses: .unknown, .candidate, .listed.

The dummy data in the `@MutationAction`s `fetchCandidates` need to be updated to reflect this (as well as the specs).

Need to create a `@MutationAction public async fetchListed()`

Both actions need to update their respective last block number with some dummy value.  The point of the last block is that it should work like poorman's blockchain paging.  We need to keep track of the last block we get for each collection as we will pass that in as the first block the next type we append to the arrays.

**Comment by thirtyaughtsix** [comment]
See #94 and #93

**Comment by thirtyaughtsix** [comment]
If the new datatrust endpoint isn't ready go ahead and use this canned json:
```
[{
"listing_hash": "0x13ff7581fd72e6ba06bade3b5150d6cb5587e1e94459bdd023d15d58ad9e5e88",
"description": "description",
"file_type": "application/pdf",
"license": "MIT",
"md5_sum": "29f59776523b2c4c315459ae66124b29",
"title": "title",
"tags": ["tag_a", "tag_b"]
}]
```

**Comment by MelvinMallari** [comment]
#129
